// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://jeapumwkcdwsyzjpzvgw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImplYXB1bXdrY2R3c3l6anB6dmd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2MjE0ODksImV4cCI6MjA3MDE5NzQ4OX0.KWV1PaZOdYEBp5JUCzgdTK4bNTYHMOtOInq_jnK4Zvc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);